name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Set up PHP (Optional – for syntax check only)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Deploy Laravel App via rsync
        run: |
          rsync -avz --delete \
            --exclude='.git*' \
            --exclude='node_modules' \
            --exclude='vendor' \
            --exclude='.env' \
            -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa" \
            ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_DEPLOY_PATH }}

      - name: Run Laravel Artisan Commands on Server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.REMOTE_DEPLOY_PATH }}
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
          EOF
